### PR TITLE
added pasting functionality

### PR DESCRIPTION
**Pull request by Saradomin1997**
Tested in Firefox 116.0.3 and Chrome 116.0.5845.96

### CODE REVIEW

**Comment by akinuri** [comment]
Hi. This is an interesting and a good feature. I'd like to include this.

Before merging this, I'll ask you to do some small changes. I did some refactoring to the existing code (this PR triggered it :), so it'll conflict. You should update your fork, and add your changes again.

I usually do post-changes/commits on PRs to make them fit well with the existing code, so let me make some comments on your code before merging.

1. Why `bind()`?
2. Why `e.stopPropagation()`?
3. Why direct access to a file `file = e.originalEvent.clipboardData.files[0]`?
4. Why `new FileReader()`?

I don't want to give away too much with the questions, so I've kept them short. Examine the existing code and think about them a little.

You don't have to refactor your code, just resolve the conflict. I'll do the required changes anyway.

**Comment by rtyaoke** [comment]
Excuse me for cutting in.


"paste from clipboard" is good idea!

In that case, how about this UI idea? 

I've came up with this UI idea so that unique users can easy understand this clipboard function.

Here is a mock image.

image

**Comment by akinuri** [comment]
Hi @rtyaoke

Yes, it'd be wise to indicate in the UI that there's a "paste" functionality. However, I don't think there's a way to trigger the (file) paste programmatically. I'm saying this because of the button-like "Clipboard" text. Nevertheless, there can be info about the pasted file. So, yeah, I suppose the UI (left side) can be redesigned a little.

Currently, this is what I have in mind:

[Preview] (still has the drag-and-drop functionality)
Choose File: __________
Image URL: __________
Clipboard: __________
Reset

Thought it'd be a good idea to provide info about the file (name) and the origin of the input.

**Comment by rtyaoke** [comment]
Hi @akinuri 

I apologize for my lack of explanation. Regarding the "Clipboard" in the UI mockup image I provided, I envisioned it as a "button." Perhaps it should have been designed more like the "Reset" button, rather than just an outline.

***

> I don't think there's a way to trigger the (file) paste programmatically.

I agree with you on that. Instead of listening to the window's "paste" event for triggering the image paste function from the clipboard, it would be preferable to have an event that users can explicitly choose, like a button, **paste** area, and so on.


***

> Currently, this is what I have in mind:
> 
> [Preview] (still has the drag-and-drop functionality)
> Choose File: __________
> Image URL: __________
> Clipboard: __________
> Reset
> 
> Thought it'd be a good idea to provide info about the file (name) and the origin of the input.

I might not fully understand due to my limited English proficiency. 
Could you explain this ↑ in more detail?

In particular,

> to provide info about the file (name)

I think that when using the Clipboard, we probably can't retrieve the file name.
Is that correct?

https://developer.mozilla.org/ja/docs/Web/API/Clipboard

**Comment by rtyaoke** [comment]
Just a note.
Given only the button label "Clipboard" in the mockup I provided, users might momentarily wonder:

- "Can I paste the 'URL' of an image from the clipboard?"
- "Can I paste the image data stored in the clipboard?"
- "Can I directly paste a file icon I copied from 'explore' (in Windows) or 'finder' (in Mac)?"
  - (Note: Due to API limitations, it's uncertain whether this can be implemented. When performing ctrl + c on the file system, there's a possibility that nothing is saved to the clipboard. From my experience, I believe the Windows clipboard does not save file paths.)

It might be unclear which of these possibilities the term "Clipboard" refers to, leading to potential confusion.

That being said, I might be overthinking this...

**Comment by akinuri** [comment]
I think an image will explain better.

akinuri_image-to-base64_index html

`e.originalEvent.clipboardData.files[0]` in `$(window).on("paste", function(e) {` returns a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object. So the file name is accessible.

**Comment by rtyaoke** [comment]
How can we indicate to users "what input is currently base64 encoded"?
The attached image and figma file is a memo for my own thought process and an indication idea.
(I believe there might be a better idea...
In my design, it might be a bit unclear whether it's clickable or not.)
image
[Untitled.fig.zip](https://github.com/akinuri/image-to-base64/files/12418535/Untitled.fig.zip)


P.S.
Should I have opened a new issue about this input separation topic?

**Comment by akinuri** [comment]
> How can we indicate to users "what input is currently base64 encoded"?

When there's an input, [resetUI()](https://github.com/akinuri/image-to-base64/blob/master/script.js#L88) clears all inputs except the origin. So, if the mentioned inputs are implemented, only one of them can be filled at a time. Normally, this might be enough to indicate the origin, but the labels can also be darkened like in your image.

Also, don't worry about the "clickable or not" thing. I expect someone who's working with base64 to be able to discern what's clickable or not :)

And, yes. You should open an issue about this.

**Comment by rtyaoke** [comment]
Thank you for your kind response!
Your implementation idea seems good enough for users to understand the current active input.

**Pull request merged**
